### ISSUE TITLE
Joining

### ISSUE THREAD

**Issue by LAMGE2** [foxverse/n3ds.foxverse.xyz#1]
How can we join?

If we need CFW or Homebrew, please find a DNS solution...

**Comment by MikeModder** [comment]
Die to the fact that Miiverse uses HTTPS like, using a DNS redirect can't be done.

**Comment by ctrninja** [comment]
This is impossible sadly, unless Nintendo releases a update that uses our servers or someone leaks the Miiverse server certs which is most likely never. Sorry to burst your bubble.
